import { analyzeBehavioral, type BehavioralEntry } from './behavioral.js';
import type { AnalysisResult, DerivedInterpretation } from '../types.js';
import interactionsData from '../data/supplement-interactions.js';
import outcomeSourcesData from '../data/outcome-sources.js';

// Sourced knowledge base, generated by scripts/build-kb.mjs (npm run kb:build):
// supplement-drug interactions from SUPP.AI (literature-extracted) and outcome
// citations from Pillser. Loaded at startup; no network calls per request.
interface SuppAiInteraction { cui: string; name: string; aliases: string[]; evidence_count: number; url: string }
interface SuppAiSupplement { cui: string; matched_name: string; drug_interactions: SuppAiInteraction[] }
interface InteractionsDoc { source: string; source_url: string; generated_at: string; supplements: Record<string, SuppAiSupplement> }
interface OutcomeSource { title: string; url: string; study_count: number | null }
interface OutcomesDoc { source: string; source_url: string; outcomes: Record<string, OutcomeSource> }

const INTERACTIONS = interactionsData as unknown as InteractionsDoc;
const OUTCOMES = outcomeSourcesData as unknown as OutcomesDoc;

// Flagged marker:direction -> the Pillser outcome page cited as its evidence base.
const MARKER_OUTCOME_SLUG: Record<string, string> = {
  'apob:high': 'reduced-ldl-cholesterol-levels',
  'ldl_c:high': 'reduced-ldl-cholesterol-levels',
  'non_hdl_c:high': 'reduced-ldl-cholesterol-levels',
  'total_cholesterol:high': 'reduced-ldl-cholesterol-levels',
  'triglycerides:high': 'reduced-triglycerides',
  'tg_hdl_ratio:high': 'reduced-triglycerides',
  'tyg_index:high': 'reduced-triglycerides',
  'hdl_c:low': 'increased-hdl-cholesterol-levels',
  'fasting_glucose:high': 'improved-insulin-sensitivity',
  'hba1c:high': 'improved-insulin-sensitivity',
  'homa_ir:high': 'improved-insulin-sensitivity',
  'fasting_insulin:high': 'improved-insulin-sensitivity',
  'hs_crp:high': 'reduced-inflammation',
  'systolic_bp:high': 'reduced-blood-pressure',
  'diastolic_bp:high': 'reduced-blood-pressure',
  'homocysteine:high': 'reduced-homocysteine-levels',
  'uric_acid:high': 'reduced-uric-acid-levels',
  'total_testosterone:low': 'increased-testosterone-levels',
  'sleep_quality:low': 'improved-sleep-quality',
  'deep_sleep_minutes:low': 'improved-sleep-quality',
};

// Customized action plans: turn a stored analysis into a prioritized set of
// lifestyle interventions and an evidence-graded supplement stack, mapped from
// each out-of-range finding (Examine.com-style). Everything is wellness-framed
// and educational; it never diagnoses, treats, or tells a user to change a
// prescribed medication. Supplements the user already logs are flagged rather
// than re-recommended, and known supplement-drug interactions surface as
// cautions against the user's medication list.

// Evidence grade mirrors a familiar A–D convention:
//   A = strong/consistent human evidence   B = moderate, some good trials
//   C = limited/preliminary or mechanistic  D = mixed/weak, mostly context
export type EvidenceGrade = 'A' | 'B' | 'C' | 'D';

export const EVIDENCE_LABELS: Record<EvidenceGrade, string> = {
  A: 'Strong, consistent human evidence',
  B: 'Moderate evidence from good trials',
  C: 'Limited or preliminary evidence',
  D: 'Mixed or mechanistic evidence',
};

type InterventionCategory = 'nutrition' | 'exercise' | 'sleep' | 'stress' | 'substance' | 'other';

// A supplement in the catalog. `interacts_with` lists medication classes/genes
// (see MEDICATION_CLASSES) that warrant a caution when the user takes one.
interface SupplementRef {
  id: string;
  name: string;
  form?: string;
  typical_dose: string;
  timing?: string;
  evidence: EvidenceGrade;
  evidence_note: string;
  mechanism?: string;
  cautions?: string[];
  interacts_with?: string[];
  aliases?: string[];
}

interface InterventionRef {
  id: string;
  name: string;
  category: InterventionCategory;
  detail: string;
  evidence: EvidenceGrade;
}

interface Trigger {
  marker: string;
  direction: 'high' | 'low';
  interventions: string[];
  supplements: string[];
}

const SUPPLEMENTS: Record<string, SupplementRef> = {
  omega_3: {
    id: 'omega_3', name: 'Omega-3 (EPA/DHA)', form: 'fish or algal oil',
    typical_dose: '2–4 g/day combined EPA+DHA', timing: 'with a meal',
    evidence: 'A', evidence_note: 'Consistently lowers triglycerides; supports inflammation and blood pressure.',
    mechanism: 'Reduces hepatic VLDL/triglyceride output and is anti-inflammatory.',
    cautions: ['High doses can raise LDL-C in some people and mildly increase bleeding risk.'],
    interacts_with: ['anticoagulant', 'antiplatelet'],
    aliases: ['fish oil', 'epa', 'dha', 'omega 3', 'omega-3'],
  },
  soluble_fiber: {
    id: 'soluble_fiber', name: 'Soluble fiber (psyllium)', form: 'psyllium husk',
    typical_dose: '5–10 g/day', timing: 'before meals with water',
    evidence: 'B', evidence_note: 'Lowers LDL-C and ApoB modestly and blunts post-meal glucose.',
    mechanism: 'Binds bile acids, increasing cholesterol clearance; slows carbohydrate absorption.',
    cautions: ['Introduce gradually and separate from medications by ~1–2 hours to avoid reduced absorption.'],
    aliases: ['psyllium', 'fiber', 'metamucil'],
  },
  plant_sterols: {
    id: 'plant_sterols', name: 'Plant sterols/stanols',
    typical_dose: '2 g/day', timing: 'with meals',
    evidence: 'A', evidence_note: 'Reduces LDL-C by roughly 8–10% by blocking cholesterol absorption.',
    mechanism: 'Competes with dietary/biliary cholesterol for intestinal absorption.',
    aliases: ['phytosterols', 'sterols', 'stanols'],
  },
  berberine: {
    id: 'berberine', name: 'Berberine',
    typical_dose: '500 mg, 2–3×/day', timing: 'with meals',
    evidence: 'B', evidence_note: 'Improves fasting glucose, HbA1c, and triglycerides in trials.',
    mechanism: 'Activates AMPK; improves insulin sensitivity and lipid handling.',
    cautions: ['Can cause GI upset; additive glucose-lowering with diabetes medication.'],
    interacts_with: ['antidiabetic', 'cyp3a4_substrate'],
  },
  bergamot: {
    id: 'bergamot', name: 'Bergamot polyphenols',
    typical_dose: '500–1000 mg/day', timing: 'before meals',
    evidence: 'C', evidence_note: 'Preliminary trials show modest LDL-C and triglyceride reductions.',
    aliases: ['citrus bergamot'],
  },
  methylfolate: {
    id: 'methylfolate', name: 'Folate (L-methylfolate)', form: '5-MTHF',
    typical_dose: '400–800 mcg/day', timing: 'morning',
    evidence: 'A', evidence_note: 'Lowers homocysteine; the methylated form suits common MTHFR variants.',
    mechanism: 'Cofactor for remethylation of homocysteine to methionine.',
    cautions: ['High-dose folate can mask a B12 deficiency; pair with B12.'],
    aliases: ['folate', 'folic acid', '5-mthf', 'methyl folate'],
  },
  vitamin_b12: {
    id: 'vitamin_b12', name: 'Vitamin B12 (methylcobalamin)',
    typical_dose: '500–1000 mcg/day', timing: 'morning',
    evidence: 'A', evidence_note: 'Corrects deficiency and lowers homocysteine alongside folate.',
    aliases: ['b12', 'cobalamin', 'methylcobalamin'],
  },
  vitamin_b6: {
    id: 'vitamin_b6', name: 'Vitamin B6 (P5P)',
    typical_dose: '25–50 mg/day', timing: 'with food',
    evidence: 'B', evidence_note: 'Supports the transsulfuration arm of homocysteine clearance.',
    cautions: ['Chronic high doses (>100 mg/day) can cause neuropathy.'],
    aliases: ['b6', 'pyridoxine', 'p5p'],
  },
  vitamin_d3: {
    id: 'vitamin_d3', name: 'Vitamin D3', form: 'cholecalciferol',
    typical_dose: '2000–4000 IU/day (titrate to blood level)', timing: 'with a fat-containing meal',
    evidence: 'A', evidence_note: 'Raises 25-OH vitamin D; dose to a repeat blood level of ~40–60 ng/mL.',
    cautions: ['Pair with vitamin K2 and adequate magnesium; avoid stacking very high doses without retesting.'],
    aliases: ['vitamin d', 'd3', 'cholecalciferol'],
  },
  vitamin_k2: {
    id: 'vitamin_k2', name: 'Vitamin K2 (MK-7)',
    typical_dose: '100–200 mcg/day', timing: 'with vitamin D',
    evidence: 'C', evidence_note: 'Directs calcium toward bone; common co-factor alongside vitamin D.',
    cautions: ['Antagonizes warfarin - do not add if you take a vitamin K antagonist without clinician review.'],
    interacts_with: ['vitamin_k_antagonist'],
    aliases: ['k2', 'mk-7', 'menaquinone'],
  },
  magnesium_glycinate: {
    id: 'magnesium_glycinate', name: 'Magnesium (glycinate)',
    typical_dose: '200–400 mg elemental/day', timing: 'evening',
    evidence: 'B', evidence_note: 'Supports insulin sensitivity, blood pressure, sleep, and repletes low status.',
    cautions: ['Reduce dose with kidney impairment; separate from some antibiotics by a few hours.'],
    interacts_with: ['certain_antibiotic'],
    aliases: ['magnesium', 'mag glycinate', 'magnesium bisglycinate'],
  },
  iron_bisglycinate: {
    id: 'iron_bisglycinate', name: 'Iron (bisglycinate)',
    typical_dose: '25–50 mg elemental every other day', timing: 'with vitamin C, away from coffee/tea',
    evidence: 'A', evidence_note: 'Repletes low ferritin/iron stores; alternate-day dosing improves absorption.',
    cautions: ['Only supplement iron for a confirmed low level; excess iron is harmful. Separate from levothyroxine and some antibiotics.'],
    interacts_with: ['levothyroxine', 'certain_antibiotic'],
    aliases: ['iron', 'ferrous', 'iron bisglycinate'],
  },
  vitamin_c: {
    id: 'vitamin_c', name: 'Vitamin C',
    typical_dose: '250–500 mg/day', timing: 'with iron-rich meals',
    evidence: 'C', evidence_note: 'Aids non-heme iron absorption and modestly lowers uric acid.',
    aliases: ['ascorbic acid', 'vitamin c'],
  },
  tart_cherry: {
    id: 'tart_cherry', name: 'Tart cherry extract',
    typical_dose: '480 mg/day (or 1 cup juice)', timing: 'evening',
    evidence: 'C', evidence_note: 'Preliminary evidence for lowering uric acid and supporting sleep.',
    aliases: ['montmorency cherry'],
  },
  curcumin: {
    id: 'curcumin', name: 'Curcumin (with piperine)',
    typical_dose: '500–1000 mg/day', timing: 'with a meal',
    evidence: 'B', evidence_note: 'Reduces CRP and inflammatory markers in several trials.',
    cautions: ['Mild antiplatelet effect at high doses.'],
    interacts_with: ['anticoagulant', 'antiplatelet'],
    aliases: ['turmeric', 'curcumin'],
  },
  inositol: {
    id: 'inositol', name: 'Myo-inositol',
    typical_dose: '2–4 g/day', timing: 'split, with meals',
    evidence: 'B', evidence_note: 'Improves insulin sensitivity, especially with PCOS-pattern metabolism.',
    aliases: ['myo-inositol', 'inositol'],
  },
  ashwagandha: {
    id: 'ashwagandha', name: 'Ashwagandha (KSM-66)',
    typical_dose: '300–600 mg/day', timing: 'evening',
    evidence: 'B', evidence_note: 'Reduces perceived stress and cortisol; small trials support sleep and testosterone.',
    cautions: ['Avoid with hyperthyroidism or if pregnant; check with a clinician if on thyroid or sedative medication.'],
    interacts_with: ['thyroid', 'sedative'],
    aliases: ['ashwagandha', 'withania'],
  },
  glycine: {
    id: 'glycine', name: 'Glycine',
    typical_dose: '3 g/day', timing: '~1 hour before bed',
    evidence: 'C', evidence_note: 'Small trials show improved subjective sleep quality and morning alertness.',
    aliases: ['glycine'],
  },
  l_theanine: {
    id: 'l_theanine', name: 'L-theanine',
    typical_dose: '100–200 mg', timing: 'evening or with caffeine',
    evidence: 'C', evidence_note: 'Promotes calm focus and can soften caffeine-related arousal.',
    aliases: ['theanine', 'l-theanine'],
  },
  coq10: {
    id: 'coq10', name: 'CoQ10 (ubiquinol)',
    typical_dose: '100–200 mg/day', timing: 'with a fat-containing meal',
    evidence: 'C', evidence_note: 'Modest blood-pressure support; sometimes used to offset statin-related muscle symptoms.',
    aliases: ['coq10', 'ubiquinol', 'coenzyme q10'],
  },
  creatine: {
    id: 'creatine', name: 'Creatine monohydrate',
    typical_dose: '3–5 g/day', timing: 'any time, daily',
    evidence: 'A', evidence_note: 'Well-supported for strength, lean mass, and training capacity.',
    aliases: ['creatine'],
  },
};

const INTERVENTIONS: Record<string, InterventionRef> = {
  reduce_sat_fat: { id: 'reduce_sat_fat', name: 'Cut saturated fat, raise unsaturated', category: 'nutrition', detail: 'Swap butter, fatty processed meat, and palm/coconut fat for olive oil, nuts, seeds, and fatty fish.', evidence: 'A' },
  soluble_fiber_food: { id: 'soluble_fiber_food', name: 'Eat more soluble fiber', category: 'nutrition', detail: 'Oats, legumes, barley, apples, and psyllium lower LDL-C and ApoB and steady glucose.', evidence: 'A' },
  reduce_refined_carbs: { id: 'reduce_refined_carbs', name: 'Reduce refined carbs & added sugar', category: 'nutrition', detail: 'Replace sugary drinks, white bread, and desserts with whole foods to cut triglycerides and glucose swings.', evidence: 'A' },
  post_meal_walk: { id: 'post_meal_walk', name: 'Walk after meals', category: 'exercise', detail: 'A 10–15 minute walk after eating meaningfully blunts post-meal glucose.', evidence: 'B' },
  resistance_training: { id: 'resistance_training', name: 'Resistance training 2–4×/week', category: 'exercise', detail: 'Building muscle improves insulin sensitivity, body composition, testosterone, and healthspan.', evidence: 'A' },
  zone2_cardio: { id: 'zone2_cardio', name: 'Zone 2 cardio', category: 'exercise', detail: '150+ minutes/week of easy aerobic work improves triglycerides, HDL, blood pressure, and VO2.', evidence: 'A' },
  weight_loss: { id: 'weight_loss', name: 'Reduce visceral fat', category: 'nutrition', detail: 'A modest 5–10% loss of excess weight improves nearly every cardiometabolic marker.', evidence: 'A' },
  reduce_alcohol: { id: 'reduce_alcohol', name: 'Reduce alcohol', category: 'substance', detail: 'Alcohol raises triglycerides, uric acid, and blood pressure and degrades sleep and HRV.', evidence: 'B' },
  reduce_sodium_dash: { id: 'reduce_sodium_dash', name: 'Lower sodium, DASH pattern', category: 'nutrition', detail: 'Cut processed-food sodium and emphasize potassium-rich vegetables, fruit, and legumes.', evidence: 'A' },
  potassium_foods: { id: 'potassium_foods', name: 'Potassium-rich foods', category: 'nutrition', detail: 'Leafy greens, beans, avocado, and potato support healthy blood pressure (dietary, not pills).', evidence: 'B' },
  quit_smoking: { id: 'quit_smoking', name: 'Stop smoking/vaping', category: 'substance', detail: 'The single largest lever for HDL function, inflammation, and cardiovascular risk.', evidence: 'A' },
  sleep_hygiene: { id: 'sleep_hygiene', name: 'Sleep consistency & light hygiene', category: 'sleep', detail: 'Fixed wake time, morning daylight, a cool dark room, and no late caffeine improve depth and HRV.', evidence: 'A' },
  caffeine_timing: { id: 'caffeine_timing', name: 'Stop caffeine 8–10h before bed', category: 'sleep', detail: 'Late caffeine fragments deep sleep even when you fall asleep fine.', evidence: 'B' },
  stress_breathwork: { id: 'stress_breathwork', name: 'Daily down-regulation', category: 'stress', detail: 'Slow breathing, daylight, and time outdoors lower cortisol and raise HRV.', evidence: 'B' },
  hydration: { id: 'hydration', name: 'Improve hydration', category: 'nutrition', detail: 'Adequate water supports uric acid clearance and general recovery.', evidence: 'C' },
  reduce_purines_fructose: { id: 'reduce_purines_fructose', name: 'Cut fructose & purine load', category: 'nutrition', detail: 'Reduce sugary drinks, alcohol, and organ/red meat to lower uric acid.', evidence: 'B' },
  sunlight: { id: 'sunlight', name: 'Sensible sun exposure', category: 'other', detail: 'Regular midday sunlight supports vitamin D alongside supplementation.', evidence: 'B' },
  training_load: { id: 'training_load', name: 'Manage training load', category: 'exercise', detail: 'Balance hard sessions with recovery days; overreaching suppresses HRV and recovery.', evidence: 'B' },
  protein_target: { id: 'protein_target', name: 'Hit a protein target', category: 'nutrition', detail: 'Aim for ~1.6 g/kg/day across meals to protect lean mass and satiety.', evidence: 'B' },
};

const TRIGGERS: Trigger[] = [
  { marker: 'apob', direction: 'high', interventions: ['reduce_sat_fat', 'soluble_fiber_food', 'weight_loss', 'zone2_cardio'], supplements: ['soluble_fiber', 'plant_sterols', 'omega_3', 'bergamot'] },
  { marker: 'ldl_c', direction: 'high', interventions: ['reduce_sat_fat', 'soluble_fiber_food', 'weight_loss'], supplements: ['plant_sterols', 'soluble_fiber', 'bergamot'] },
  { marker: 'non_hdl_c', direction: 'high', interventions: ['reduce_sat_fat', 'soluble_fiber_food'], supplements: ['plant_sterols', 'soluble_fiber'] },
  { marker: 'total_cholesterol', direction: 'high', interventions: ['reduce_sat_fat', 'soluble_fiber_food'], supplements: ['plant_sterols', 'soluble_fiber'] },
  { marker: 'triglycerides', direction: 'high', interventions: ['reduce_refined_carbs', 'reduce_alcohol', 'zone2_cardio', 'weight_loss'], supplements: ['omega_3', 'berberine'] },
  { marker: 'tg_hdl_ratio', direction: 'high', interventions: ['reduce_refined_carbs', 'zone2_cardio'], supplements: ['omega_3', 'berberine'] },
  { marker: 'tyg_index', direction: 'high', interventions: ['reduce_refined_carbs', 'post_meal_walk', 'resistance_training'], supplements: ['berberine', 'inositol'] },
  { marker: 'hdl_c', direction: 'low', interventions: ['zone2_cardio', 'quit_smoking', 'reduce_refined_carbs'], supplements: ['omega_3'] },
  { marker: 'fasting_glucose', direction: 'high', interventions: ['reduce_refined_carbs', 'post_meal_walk', 'resistance_training', 'weight_loss'], supplements: ['berberine', 'inositol', 'magnesium_glycinate'] },
  { marker: 'hba1c', direction: 'high', interventions: ['reduce_refined_carbs', 'post_meal_walk', 'resistance_training', 'weight_loss'], supplements: ['berberine', 'inositol', 'magnesium_glycinate'] },
  { marker: 'homa_ir', direction: 'high', interventions: ['reduce_refined_carbs', 'resistance_training', 'weight_loss', 'sleep_hygiene'], supplements: ['berberine', 'inositol', 'magnesium_glycinate'] },
  { marker: 'fasting_insulin', direction: 'high', interventions: ['reduce_refined_carbs', 'resistance_training', 'weight_loss'], supplements: ['berberine', 'inositol'] },
  { marker: 'hs_crp', direction: 'high', interventions: ['sleep_hygiene', 'weight_loss', 'zone2_cardio'], supplements: ['omega_3', 'curcumin'] },
  { marker: 'homocysteine', direction: 'high', interventions: [], supplements: ['methylfolate', 'vitamin_b12', 'vitamin_b6'] },
  { marker: 'vitamin_d', direction: 'low', interventions: ['sunlight'], supplements: ['vitamin_d3', 'vitamin_k2', 'magnesium_glycinate'] },
  { marker: 'b12', direction: 'low', interventions: [], supplements: ['vitamin_b12'] },
  { marker: 'folate', direction: 'low', interventions: [], supplements: ['methylfolate'] },
  { marker: 'magnesium', direction: 'low', interventions: [], supplements: ['magnesium_glycinate'] },
  { marker: 'uric_acid', direction: 'high', interventions: ['reduce_purines_fructose', 'reduce_alcohol', 'hydration', 'weight_loss'], supplements: ['vitamin_c', 'tart_cherry'] },
  { marker: 'ferritin', direction: 'low', interventions: [], supplements: ['iron_bisglycinate', 'vitamin_c'] },
  { marker: 'total_testosterone', direction: 'low', interventions: ['resistance_training', 'sleep_hygiene', 'weight_loss', 'reduce_alcohol'], supplements: ['vitamin_d3', 'ashwagandha'] },
  { marker: 'systolic_bp', direction: 'high', interventions: ['reduce_sodium_dash', 'potassium_foods', 'weight_loss', 'zone2_cardio', 'reduce_alcohol'], supplements: ['omega_3', 'magnesium_glycinate', 'coq10'] },
  { marker: 'diastolic_bp', direction: 'high', interventions: ['reduce_sodium_dash', 'weight_loss', 'zone2_cardio'], supplements: ['omega_3', 'magnesium_glycinate'] },
  { marker: 'hrv', direction: 'low', interventions: ['reduce_alcohol', 'sleep_hygiene', 'stress_breathwork', 'training_load'], supplements: ['magnesium_glycinate'] },
  { marker: 'resting_hr', direction: 'high', interventions: ['zone2_cardio', 'sleep_hygiene', 'reduce_alcohol'], supplements: [] },
  { marker: 'deep_sleep_minutes', direction: 'low', interventions: ['sleep_hygiene', 'caffeine_timing', 'reduce_alcohol'], supplements: ['magnesium_glycinate', 'glycine'] },
  { marker: 'sleep_quality', direction: 'low', interventions: ['sleep_hygiene', 'caffeine_timing'], supplements: ['magnesium_glycinate', 'glycine', 'l_theanine'] },
  { marker: 'stress_level', direction: 'high', interventions: ['stress_breathwork', 'sleep_hygiene'], supplements: ['ashwagandha', 'magnesium_glycinate'] },
  { marker: 'cortisol_morning', direction: 'high', interventions: ['stress_breathwork', 'sleep_hygiene'], supplements: ['ashwagandha'] },
  { marker: 'fiber_g', direction: 'low', interventions: ['soluble_fiber_food'], supplements: ['soluble_fiber'] },
  { marker: 'protein_g', direction: 'low', interventions: ['protein_target', 'resistance_training'], supplements: ['creatine'] },
  { marker: 'added_sugar_g', direction: 'high', interventions: ['reduce_refined_carbs'], supplements: [] },
  { marker: 'alcohol_units_week', direction: 'high', interventions: ['reduce_alcohol'], supplements: [] },
];

const TRIGGER_INDEX = new Map(TRIGGERS.map(trigger => [`${trigger.marker}:${trigger.direction}`, trigger]));

// Map a user's medication name to interaction classes so supplement cautions can
// reference the medication they actually take.
const MEDICATION_CLASSES: Array<{ test: RegExp; classes: string[] }> = [
  { test: /statin$/i, classes: ['statin'] },
  { test: /warfarin|coumadin|acenocoumarol/i, classes: ['anticoagulant', 'vitamin_k_antagonist'] },
  { test: /apixaban|rivaroxaban|dabigatran|edoxaban|heparin/i, classes: ['anticoagulant'] },
  { test: /clopidogrel|aspirin|ticagrelor|prasugrel/i, classes: ['antiplatelet'] },
  { test: /metformin|glipizide|gliclazide|glimepiride|insulin|empagliflozin|dapagliflozin|sitagliptin/i, classes: ['antidiabetic'] },
  { test: /levothyroxine|synthroid|levoxyl/i, classes: ['levothyroxine', 'thyroid'] },
  { test: /methimazole|carbimazole|propylthiouracil/i, classes: ['thyroid'] },
  { test: /ciprofloxacin|doxycycline|tetracycline|levofloxacin/i, classes: ['certain_antibiotic'] },
  { test: /zolpidem|lorazepam|diazepam|clonazepam|trazodone/i, classes: ['sedative'] },
  { test: /cyclosporine|tacrolimus/i, classes: ['cyp3a4_substrate'] },
];

const INTERACTION_TEXT: Record<string, string> = {
  statin: 'may add to statin effects - review dosing with a clinician',
  anticoagulant: 'can increase bleeding risk with blood thinners',
  antiplatelet: 'can increase bleeding risk with antiplatelet medication',
  antidiabetic: 'can add to glucose-lowering medication (hypoglycemia risk)',
  vitamin_k_antagonist: 'directly interferes with warfarin/vitamin K antagonists',
  levothyroxine: 'reduces thyroid-hormone absorption - separate dosing by 4 hours',
  thyroid: 'may affect thyroid medication - check with a clinician',
  certain_antibiotic: 'reduces absorption of some antibiotics - separate dosing',
  sedative: 'can add to sedative medication',
  cyp3a4_substrate: 'can alter blood levels of CYP3A4-metabolized drugs',
};

export type ActionPriority = 'core' | 'optimize';

export interface ActionTarget {
  marker: string;
  finding: string;
  direction: 'low' | 'high' | 'ok';
  status?: string;
}

export interface ActionSource {
  name: string;
  url?: string;
  detail?: string;
}

export interface ActionPlanIntervention {
  id: string;
  name: string;
  category: InterventionCategory;
  detail: string;
  evidence: EvidenceGrade;
  priority: ActionPriority;
  targets: ActionTarget[];
  rationale: string;
}

export interface ActionPlanSupplement {
  id: string;
  name: string;
  form?: string;
  typical_dose?: string;
  timing?: string;
  dose_guidance: string;
  evidence: EvidenceGrade;
  evidence_note: string;
  mechanism?: string;
  priority: ActionPriority;
  targets: ActionTarget[];
  rationale: string;
  cautions: string[];
  already_taking: boolean;
  sources: ActionSource[];
}

export interface ActionPlan {
  analysis_id: string;
  user_id: string;
  organization_id?: string;
  generated_at: string;
  summary: string;
  interventions: ActionPlanIntervention[];
  supplements: ActionPlanSupplement[];
  cautions: string[];
  evidence_key: Record<EvidenceGrade, string>;
  sources: ActionSource[];
  disclaimer: string;
  provenance: { analysis_id: string; source_ids: string[]; engine: string };
}

const DISCLAIMER =
  'Educational wellness guidance, not medical advice. It does not diagnose or treat disease. ' +
  'Supplements are not a substitute for prescribed medication - never start, stop, or change a medication based on this plan. ' +
  'Confirm nutrient deficiencies with testing and discuss supplements and interactions with a clinician or pharmacist, especially during pregnancy or with existing conditions.';

interface FlaggedFinding {
  marker: string;
  direction: 'low' | 'high';
  finding: string;
  status?: string;
  score: number;
  sourceIds: string[];
}

const EVIDENCE_ORDER: Record<EvidenceGrade, number> = { A: 0, B: 1, C: 2, D: 3 };

export interface ActionPlanOptions {
  /** Exact dose/timing is withheld by default until a clinician-reviewed policy explicitly enables it. */
  includeSupplementDoses?: boolean;
}

export function buildActionPlan(analysis: AnalysisResult, options: ActionPlanOptions = {}): ActionPlan {
  const flagged = collectFlaggedFindings(analysis.derived_interpretations);
  const inventory = behavioralInventory(analysis);
  const takenSupplementKeys = supplementKeySet(inventory.supplements.map(s => s.name));
  const medicationNames = inventory.medications.map(m => m.name);
  const medicationClasses = classifyMedications(medicationNames);

  const interventionAgg = new Map<string, { ref: InterventionRef; targets: ActionTarget[]; topStatus: string }>();
  const supplementAgg = new Map<string, { ref: SupplementRef; targets: ActionTarget[]; topStatus: string }>();

  for (const flag of flagged) {
    const trigger = TRIGGER_INDEX.get(`${flag.marker}:${flag.direction}`);
    if (!trigger) continue;
    const target: ActionTarget = { marker: flag.marker, finding: flag.finding, direction: flag.direction, status: flag.status };
    for (const id of trigger.interventions) {
      const ref = INTERVENTIONS[id];
      if (!ref) continue;
      const entry = interventionAgg.get(id) ?? { ref, targets: [], topStatus: flag.status ?? 'watch' };
      entry.targets.push(target);
      if (rankStatus(flag.status) < rankStatus(entry.topStatus)) entry.topStatus = flag.status ?? entry.topStatus;
      interventionAgg.set(id, entry);
    }
    for (const id of trigger.supplements) {
      const ref = SUPPLEMENTS[id];
      if (!ref) continue;
      const entry = supplementAgg.get(id) ?? { ref, targets: [], topStatus: flag.status ?? 'watch' };
      entry.targets.push(target);
      if (rankStatus(flag.status) < rankStatus(entry.topStatus)) entry.topStatus = flag.status ?? entry.topStatus;
      supplementAgg.set(id, entry);
    }
  }

  const interventions = [...interventionAgg.values()]
    .map(entry => ({
      id: entry.ref.id,
      name: entry.ref.name,
      category: entry.ref.category,
      detail: entry.ref.detail,
      evidence: entry.ref.evidence,
      priority: priorityForStatus(entry.topStatus),
      targets: entry.targets,
      rationale: rationale(entry.targets),
    }))
    .sort(compareActions);

  const supplements = [...supplementAgg.values()]
    .map(entry => {
      // Literature-cited interactions from supp.ai take precedence; the hand map
      // fills drugs supp.ai has no extracted evidence for.
      const supp = suppAiInteractions(entry.ref.id, entry.ref.name, medicationNames);
      const cautions = [...(entry.ref.cautions ?? []), ...supp.cautions];
      for (const cls of entry.ref.interacts_with ?? []) {
        const med = medicationClasses.get(cls);
        if (med && !supp.matchedDrugs.has(normalizeName(med))) {
          cautions.push(`You logged ${med}: ${entry.ref.name} ${INTERACTION_TEXT[cls] ?? 'may interact'}.`);
        }
      }
      return {
        id: entry.ref.id,
        name: entry.ref.name,
        form: entry.ref.form,
        ...(options.includeSupplementDoses ? {
          typical_dose: entry.ref.typical_dose,
          timing: entry.ref.timing,
        } : {}),
        dose_guidance: options.includeSupplementDoses
          ? 'This reference range is educational and still requires review against age, pregnancy status, conditions, medications, kidney/liver function, and measured deficiency.'
          : 'Exact dose and timing are withheld by the API. Confirm need, product, dose, timing, interactions, and a retest plan with a qualified clinician or pharmacist.',
        evidence: entry.ref.evidence,
        evidence_note: entry.ref.evidence_note,
        mechanism: entry.ref.mechanism,
        priority: priorityForStatus(entry.topStatus),
        targets: entry.targets,
        rationale: rationale(entry.targets),
        cautions,
        already_taking: isAlreadyTaking(entry.ref, takenSupplementKeys),
        sources: dedupeSources([...supplementSuppAiSource(entry.ref.id), ...supp.sources, ...pillserSourcesForTargets(entry.targets)]),
      };
    })
    .sort(compareActions);

  const cautions = planCautions(inventory);
  const coreCount = interventions.filter(i => i.priority === 'core').length + supplements.filter(s => s.priority === 'core').length;
  const summary = flagged.length === 0
    ? 'No out-of-range findings to act on - your markers are within target. Keep the current routine and re-test on schedule.'
    : `${flagged.length} finding${flagged.length === 1 ? '' : 's'} outside target mapped to ${interventions.length} lifestyle change${interventions.length === 1 ? '' : 's'} and ${supplements.length} supplement${supplements.length === 1 ? '' : 's'}${coreCount ? `, ${coreCount} of them core priorities` : ''}. Start with the lifestyle changes; layer supplements where a target justifies them.`;

  return {
    analysis_id: analysis.id,
    user_id: analysis.user_id,
    organization_id: analysis.organization_id,
    generated_at: new Date().toISOString(),
    summary,
    interventions,
    supplements,
    cautions,
    evidence_key: EVIDENCE_LABELS,
    sources: [
      { name: INTERACTIONS.source, url: INTERACTIONS.source_url, detail: 'Supplement–drug interaction evidence extracted from the scientific literature.' },
      { name: OUTCOMES.source, url: OUTCOMES.source_url, detail: 'Supplement–health-outcome study counts, cited per finding.' },
    ],
    disclaimer: DISCLAIMER,
    provenance: {
      analysis_id: analysis.id,
      source_ids: analysis.source_ids ?? [],
      engine: 'health-api action_plan_engine',
    },
  };
}

function collectFlaggedFindings(derived: DerivedInterpretation[]): FlaggedFinding[] {
  const flagged: FlaggedFinding[] = [];
  for (const item of derived) {
    if (item.status !== 'needs_attention' && item.status !== 'watch') continue;
    const raw = (item.raw ?? {}) as { id?: string; direction?: string; unit_unrecognized?: boolean };
    if (raw.unit_unrecognized) continue;
    const marker = raw.id;
    const direction = raw.direction;
    if (!marker || (direction !== 'low' && direction !== 'high')) continue;
    flagged.push({
      marker,
      direction,
      finding: item.title,
      status: item.status,
      score: item.score ?? 100,
      sourceIds: item.provenance?.source_ids ?? [],
    });
  }
  // Most out-of-range first, so higher-severity targets lead the aggregation.
  return flagged.sort((a, b) => rankStatus(a.status) - rankStatus(b.status) || a.score - b.score);
}

function behavioralInventory(analysis: AnalysisResult): ReturnType<typeof analyzeBehavioral>['inventory'] {
  const entries = (analysis.normalized_observations ?? [])
    .filter(obs => obs.category === 'behavioral' && obs.raw && typeof obs.raw === 'object' && 'kind' in (obs.raw as object))
    .map(obs => obs.raw as BehavioralEntry);
  if (entries.length === 0) return { supplements: [], medications: [], notes: [] };
  return analyzeBehavioral(entries).inventory;
}

function supplementKeySet(names: string[]): Set<string> {
  const set = new Set<string>();
  for (const name of names) set.add(normalizeName(name));
  return set;
}

function isAlreadyTaking(ref: SupplementRef, takenKeys: Set<string>): boolean {
  const candidates = [ref.id, ref.name, ...(ref.aliases ?? [])].map(normalizeName);
  for (const key of takenKeys) {
    if (candidates.some(candidate => candidate && (key.includes(candidate) || candidate.includes(key)))) return true;
  }
  return false;
}

function classifyMedications(names: string[]): Map<string, string> {
  const map = new Map<string, string>();
  for (const name of names) {
    for (const { test, classes } of MEDICATION_CLASSES) {
      if (test.test(name)) {
        for (const cls of classes) if (!map.has(cls)) map.set(cls, name);
      }
    }
  }
  return map;
}

function planCautions(inventory: ReturnType<typeof analyzeBehavioral>['inventory']): string[] {
  const cautions: string[] = [];
  const flaggedMeds = inventory.medications.filter(m => m.pharmacogenes && m.pharmacogenes.length > 0);
  if (flaggedMeds.length > 0) {
    cautions.push(
      `You logged ${flaggedMeds.length} medication${flaggedMeds.length === 1 ? '' : 's'} with pharmacogenomic relevance (${flaggedMeds.map(m => m.name).join(', ')}). ` +
      'If you have genetic data, review gene-drug (CPIC) response and dosing context with a clinician or pharmacist.',
    );
  }
  return cautions;
}

function rationale(targets: ActionTarget[]): string {
  const labels = targets.map(t => `${t.direction === 'low' ? 'low' : 'high'} ${t.finding}`);
  return `Targets ${labels.join(', ')}.`;
}

function rankStatus(status?: string): number {
  if (status === 'needs_attention') return 0;
  if (status === 'watch') return 1;
  return 2;
}

function priorityForStatus(status?: string): ActionPriority {
  return status === 'needs_attention' ? 'core' : 'optimize';
}

function compareActions(
  a: { priority: ActionPriority; evidence: EvidenceGrade; targets: ActionTarget[] },
  b: { priority: ActionPriority; evidence: EvidenceGrade; targets: ActionTarget[] },
): number {
  if (a.priority !== b.priority) return a.priority === 'core' ? -1 : 1;
  if (b.targets.length !== a.targets.length) return b.targets.length - a.targets.length;
  return EVIDENCE_ORDER[a.evidence] - EVIDENCE_ORDER[b.evidence];
}

// Match a supp.ai drug interaction against the user's logged medications, and
// return cited cautions + source links for the ones they actually take.
function suppAiInteractions(supplementId: string, refName: string, medicationNames: string[]): { cautions: string[]; sources: ActionSource[]; matchedDrugs: Set<string> } {
  const data = INTERACTIONS.supplements[supplementId];
  const cautions: string[] = [];
  const sources: ActionSource[] = [];
  const matchedDrugs = new Set<string>();
  if (!data || medicationNames.length === 0) return { cautions, sources, matchedDrugs };
  for (const interaction of data.drug_interactions) {
    const med = medicationNames.find(name => aliasMatch(name, interaction.aliases));
    if (!med) continue;
    matchedDrugs.add(normalizeName(interaction.name));
    const reports = `${interaction.evidence_count} literature ${interaction.evidence_count === 1 ? 'report' : 'reports'}`;
    cautions.push(`You logged ${med}: ${refName} has a documented interaction with ${interaction.name} (${reports} via supp.ai). Review with a clinician or pharmacist.`);
    sources.push({ name: 'SUPP.AI', url: interaction.url, detail: `${refName} × ${interaction.name} interaction evidence` });
  }
  return { cautions, sources, matchedDrugs };
}

function aliasMatch(medName: string, aliases: string[]): boolean {
  const n = normalizeName(medName);
  if (n.length < 4) return false;
  return aliases.some(alias => {
    const a = normalizeName(alias);
    return a.length >= 4 && (a === n || a.includes(n) || n.includes(a));
  });
}

function supplementSuppAiSource(supplementId: string): ActionSource[] {
  const data = INTERACTIONS.supplements[supplementId];
  if (!data || data.drug_interactions.length === 0) return [];
  return [{ name: 'SUPP.AI', url: `https://supp.ai/a/${data.cui}`, detail: `${data.drug_interactions.length} drug interactions on file` }];
}

function pillserSourcesForTargets(targets: ActionTarget[]): ActionSource[] {
  const sources: ActionSource[] = [];
  const seen = new Set<string>();
  for (const target of targets) {
    const slug = MARKER_OUTCOME_SLUG[`${target.marker}:${target.direction}`];
    if (!slug || seen.has(slug)) continue;
    const outcome = OUTCOMES.outcomes[slug];
    if (!outcome) continue;
    seen.add(slug);
    sources.push({ name: 'Pillser', url: outcome.url, detail: outcome.study_count ? `${outcome.study_count} studies - ${outcome.title}` : outcome.title });
  }
  return sources;
}

function dedupeSources(sources: ActionSource[]): ActionSource[] {
  const byUrl = new Map<string, ActionSource>();
  for (const source of sources) {
    const key = source.url ?? source.name;
    if (!byUrl.has(key)) byUrl.set(key, source);
  }
  return [...byUrl.values()];
}

function normalizeName(value: string): string {
  return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '');
}
